### ISSUE TITLE
how do install graphchem in "google colab" ?

### ISSUE THREAD

**Issue by zxc1bnm2** [ECRL/GraphChem#5]
Or it is installed on windows10, because I have been unsuccessful in the installation~
pytorch relationship

**Comment by tjkessler** [comment]
@zxc1bnm2,

I believe this is what you are looking for: https://stackoverflow.com/questions/51342408/how-do-i-install-python-packages-in-googles-colab

**Comment by zxc1bnm2** [comment]
Thank you for your help~
