### ISSUE TITLE
not support % (ring struct)

### ISSUE THREAD

**Issue by wangqifan** [ecrl/graphchem#6]
smiles not support ring struct 
not support %
CN1CC2CC3=C(CCC45CC6C(C=C34)C63CCC4(CC67CCC8C9(C)CCCC8%10C(C6CC4CC7%10)N(C)C9)OC53)C(C)(C2)C1,

**Comment by tjkessler** [comment]
I believe the error stems from here:
https://github.com/ECRL/GraphChem/blob/master/graphchem/utils/smiles.py

The custom SMILES parser does not currently recognize the "%" symbol. Additional conditional and logic statements within the parsing loop should enable the correct interpretation of this character.

**Comment by tjkessler** [comment]
I believe this is fixed as of https://github.com/ecrl/graphchem/pull/7, now on Master branch with version (Git and PyPI) 1.1.0.
